---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: mission-ratings-web
  creationTimestamp: null
  name: mission-ratings-web
  namespace: rating-app
spec:
  lookupPolicy:
    local: false
---