---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mission-ratings-web
  name: mission-ratings-web
  namespace: rating-app
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deployment: mission-ratings-web
---